---
abstract: 'The data for converting between traditional and simplified Chinese languages.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.140640'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-HanConvert
resources:
  bugtracker: https://github.com/perltaiwan/Data-HanConvert
  repository: git://github.com/perltaiwan/Data-HanConvert.git
version: 1.3
