---
abstract: 'Chinese Data in Code'
author:
  - 'Kang-min Liu <gugod@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-HanConvert
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  perl: v5.8.1
resources:
  bugtracker: https://github.com/gugod/Data-HanConvert/issues
  homepage: https://github.com/gugod/Data-HanConvert
  repository: https://github.com/gugod/Data-HanConvert.git
version: '1.4'
